function [name2smpl, smpl2name] = smpl_mapping()
names = {
    'nose_tip',
    'lower_lip',
    'eye_left_outside',
    'eye_left_inside',
    'eye_right_outside',
    'eye_right_inside',
    'ear_left_tip',
    'ear_right_tip',
    'back_neck',
    'belly',
    'back_midpoint',
    'shoulder_left',
    'shoulder_right',
    'armpit_left',
    'armpit_right',
    'wrist_left',
    'wrist_right',
    'foot_left_front',
    'foot_right_front',
    'hip_left',
    'hip_right',
    'knee_left_back',
    'knee_right_back',
    'foot_left_back',
    'foot_right_back',
    'tail_midpoint',
    'tail_begin_top',
    'tail_tip',
    'pelvis',
    'middle_chest',
    'base_neck',
    'between_ears',
    'tail_one_eighth',
    'between_shoulder_blades',
    'hips_back_left',
    'hips_back_right',
};

ids = [
    1845,
    910, 
    1068,
    1226,
    2660,
    3030,
    543, 
    2508,
    1,   
    2,   
    1798,
    73,  
    2050,
    356, 
    2323,
    384, 
    2351,
    1235,
    2578,
    364, 
    2331,
    108, 
    2085,
    856, 
    2820,
    0,   
    452, 
    28,  
    216, 
    8,   
    6,   
    1838,
    1819,
    20,  
    176, 
    2150,] + 1;

ids = num2cell(ids);

name2smpl = containers.Map(names, ids);
smpl2name = containers.Map(ids, names);

% In the same order as gloss..
% v_ids_smpl = [
%     'eye_right_inside': 3030,
%     'eye_right_outside': 2660,
%     'eye_left_inside': 1226,
%     'eye_left_outside': 1068,
%     'ear_right_tip': 2508,
%     'ear_left_tip': 543,
%     'lower_lip': 910,
%     'nose_tip': 1845,
    
%     'tail_begin_top': 452,
%     'tail_tip': 28,
%     'tail_midpoint': 0,
    
%     'knee_left_back': 108,
%     'knee_right_back': 2085,
    
%     'foot_right_front': 2578,
%     'foot_left_back': 856,
%     'foot_right_back': 2820,
%     'foot_left_front': 1235,

%     'armpit_left': 356,
%     'armpit_right': 2323,
%     'hip_left': 364,
%     'hip_right': 2331,
    
%     'back_midpoint': 1798,
%     'back_neck': 1,
%     'belly': 2,
    
%     'wrist_right': 2351,    
%     'wrist_left': 384,
    
%     'shoulder_left': 73,
%     'shoulder_right': 2050,
%              ]
